### ISSUE TITLE
New member name is shown as '-' 

### ISSUE THREAD

**Issue by lizan** [nocnocooo/nocnoc-issues#1]
**To Reproduce**
1. Someone joins a room and say something
2. Their name is not shown (shown as '-')

**Expected behavior**
Their name shown as they entered

**Screenshots**
![image](https://user-images.githubusercontent.com/1016047/78419030-6bd8db00-75f6-11ea-9346-d81474eb252e.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 81

**Additional context:**
Refreshing the page fixes this.

**Comment by zigen** [comment]
Hi @lizan !
thank you for using our app and reporting the issue!
I'll try to fix this bug in this week.

**Comment by zigen** [comment]
this issue fixed.
