### ISSUE TITLE
text message with an image is not shown

### ISSUE THREAD

**Issue by nanaju** [nocnocooo/nocnoc-issues#2]
**Describe the bug**
Text message post with am image is not shown at the web app but can see from the iOS app.

**To Reproduce**
1. User post a text with an image to the chat(both from iOS and web app)
2. web users can see only the image without the text. iOS user can see the text and the image

**Expected behavior**
The text is shown with the image on the web app

**Screenshots**
<img width="1601" alt="Screen Shot 2020-04-06 at 4 36 50 PM" src="https://user-images.githubusercontent.com/7966501/78614913-d3746d80-7824-11ea-810a-b22dd2c65f91.png">
![IMG_4463](https://user-images.githubusercontent.com/7966501/78614932-e129f300-7824-11ea-83cd-065dee942fc6.PNG)

**Desktop (please complete the following information):**
 - OS: [Mac OS 10]
 - Browser [chrome]

**Additional context**

**Comment by zigen** [comment]
you can see text message with an image! check it!
