### ISSUE TITLE
New line is not supported 

### ISSUE THREAD

**Issue by nanaju** [nocnocooo/nocnoc-issues#3]
**Describe the bug**
A newline is not supported at the web app.

**To Reproduce**
1. send a text with newline from the web app or iOS app
2. the new line is not shown on the web app, but shown on the iOS app.

**Expected behavior**
the new line is shown on the web app
**Screenshots**
web:
<img width="257" alt="Screen Shot 2020-04-06 at 6 32 22 PM" src="https://user-images.githubusercontent.com/7966501/78623492-974d0700-783c-11ea-95b7-70ba09e07c28.png">

iOS app:
![IMG_4466](https://user-images.githubusercontent.com/7966501/78625719-ac786480-7841-11ea-9f33-f4f6147cba82.jpg)

**Desktop (please complete the following information):**
 - OS: [mac OS 10]
 - Browser [chrome]
 

**Smartphone (please complete the following information):**
 - Device: [iPhoneXR]
 - OS: [iOS13]
 - Version [app ver 1.2 build 9]

**Comment by zigen** [comment]
now you can see new line on web!
