### ISSUE TITLE
When I attempted to change the display name, the current name deleted.

### ISSUE THREAD

**Issue by nanaju** [nocnocooo/nocnoc-issues#9]
**Describe the bug**
When I attempted to change the display name on the web app, the previous name deleted.

**To Reproduce**
1. Tap "Edit my name" on the web app
2. the current name is not presented in the editing form(deleted)

**Expected behavior**
The current name is shown at the form.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Browser [chrome]
<img width="471" alt="Screen Shot 2020-04-27 at 8 23 13 PM" src="https://user-images.githubusercontent.com/7966501/80443804-ec70bb80-88c4-11ea-9747-4c6b4959925e.png">

**Additional context**

**Comment by zigen** [comment]
fixed! thank you for reporting.
